{
  "__comment_tempmail": "Jika menggunakan tempmail pribadi (Cloudflare/AyriMail), masukkan URL API dan API Key di parameter di bawah ini.",
  "duckmail_api_key": "",
  "cloudflare_api_base": "",
  "cloudflare_api_key": "",
  "cloudflare_auth_mode": "none",
  "cloudflare_path_domains": "/api/domains",
  "cloudflare_path_accounts": "/api/new_address",
  "cloudflare_path_token": "/api/token",
  "cloudflare_path_messages": "/api/mails",
  "proxy": "",
  "enable_nsfw": true,
  "register_count": 1,
  "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36",
  "grok2api_auto_add_local": false,
  "grok2api_local_token_file": "",
  "grok2api_pool_name": "ssoBasic",
  "grok2api_auto_add_remote": false,
  "grok2api_remote_base": "",
  "grok2api_remote_app_key": "",
  "cpa_export_enabled": true,
  "cpa_auth_dir": "cpa_auths",
  "cpa_proxy": "",
  "cpa_headless": false,
  "cpa_probe_after_write": true,
  "cpa_mint_timeout_sec": 240,
  "cpa_base_url": "https://cli-chat-proxy.grok.com/v1",
  "cpa_force_standalone": false,
  "cpa_mint_cookie_inject": true,
  "cpa_mint_browser_reuse": true,
  "cpa_mint_browser_recycle_every": 15,
  "cpa_hotload_dir": "",
  "cpa_copy_to_hotload": false,
  "cpa_server_host": "",
  "cpa_server_user": "root",
  "cpa_server_password": "",
  "cpa_server_auth_dir": "",
  "token_only_file": "",
  "concurrent_count": 1,
  "browser_restart_every": 10,
  "cpa_mint_async": true,
  "browser_use_custom_ua": false,
  "license_key": "",
  "license_activated_data": "",
  "license_server_url": "",
  "log_level": "info",
  "speed_log_interval_sec": 60,
  "defaultDomains": "",
  "email_provider": "mailtm",
  "ayrimail_api_base": "",
  "ayrimail_api_key": "",
  "ayrimail_domain": "",
  "yyds_api_key": "",
  "yyds_jwt": "",
  "cpa_headers": {
    "x-grok-client-version": "0.2.93",
    "x-xai-token-auth": "xai-grok-cli",
    "x-authenticateresponse": "authenticate-response",
    "x-grok-client-identifier": "grok-shell",
    "User-Agent": "grok-shell/0.2.93 (linux; x86_64)"
  }
}
